In [51]:
import torch

random_seed = 30
torch.manual_seed(random_seed)
arr = torch.randint(0, 100, (2, 3, 5))
#arr = torch.arange(30).reshape(2, 3, 5)
print(arr.shape)  # torch.Size([2, 3, 5])
print(arr.dim())   # 3
print(arr.size(0)) # 2
print(arr.size(1)) # 3
print(arr.size(2)) # 5
print(arr.shape[0]) # 2
print(arr)

torch.Size([2, 3, 5])
3
2
3
5
2
tensor([[[97, 37, 17, 53, 76],
         [84, 19,  2, 77, 47],
         [65, 26, 51,  5, 59]],

        [[47, 29,  9, 85, 89],
         [55, 18, 70, 48, 52],
         [ 2, 12, 24, 14, 58]]])


In [52]:
print(torch.sum(arr))  
print(torch.sum(arr, dim=0)) 
print(torch.sum(arr, dim=1)) 
print(torch.sum(arr, dim=2)) 

tensor(1327)
tensor([[144,  66,  26, 138, 165],
        [139,  37,  72, 125,  99],
        [ 67,  38,  75,  19, 117]])
tensor([[246,  82,  70, 135, 182],
        [104,  59, 103, 147, 199]])
tensor([[280, 229, 206],
        [259, 243, 110]])


In [53]:
print(arr)
print(torch.argmax(arr)) 
print(torch.argmax(arr, dim=0)) 
print(torch.argmax(arr, dim=1)) 
print(torch.argmax(arr, dim=2)) 

tensor([[[97, 37, 17, 53, 76],
         [84, 19,  2, 77, 47],
         [65, 26, 51,  5, 59]],

        [[47, 29,  9, 85, 89],
         [55, 18, 70, 48, 52],
         [ 2, 12, 24, 14, 58]]])
tensor(0)
tensor([[0, 0, 0, 1, 1],
        [0, 0, 1, 0, 1],
        [0, 0, 0, 1, 0]])
tensor([[0, 0, 2, 1, 0],
        [1, 0, 1, 0, 0]])
tensor([[0, 0, 0],
        [4, 2, 4]])


In [ ]:
print(arr)
print(torch.max(arr))  # tensor(97)
print(torch.max(arr, dim=0)[0])  # [[97,37,17,85,89],...]
print(torch.max(arr, dim=1)[0])  # [[97, 37, 51, 77, 76], [55, 29, 70, 85, 89]]

print(torch.max(arr, dim=2)[0])  # [[97, 84, 65], [89, 70, 58]]

tensor([[[97, 37, 17, 53, 76],
         [84, 19,  2, 77, 47],
         [65, 26, 51,  5, 59]],

        [[47, 29,  9, 85, 89],
         [55, 18, 70, 48, 52],
         [ 2, 12, 24, 14, 58]]])
tensor(97)
tensor([[97, 37, 17, 85, 89],
        [84, 19, 70, 77, 52],
        [65, 26, 51, 14, 59]])
tensor([[97, 37, 51, 77, 76],
        [55, 29, 70, 85, 89]])
tensor([[97, 84, 65],
        [89, 70, 58]])
