In [1]:
import torch

random_seed = 42
torch.manual_seed(random_seed)


# 1. 均匀分布
# 生成一个形状为(3, 4)的张量，元素在[0, 1)之间均匀分布
uniform_tensor = torch.rand(3, 4)
print("Uniform Tensor:\n", uniform_tensor)

# 2. 正态分布
# 生成一个形状为(3, 4)的张量，元素服从均值为0，标准差为1的正态分布
normal_tensor = torch.randn(3, 4)
print("\nNormal Tensor:\n", normal_tensor)

# 3. 二项分布
# 生成一个形状为(3, 4)的张量，元素服从二项分布，n=10, p=0.5
binomial_tensor = torch.bernoulli(torch.full((3, 4), 0.5))
print("\nBinomial Tensor:\n", binomial_tensor)

# 4. 指数分布
# 生成一个形状为(3, 4)的张量，元素服从参数为1的指数分布
exponential_tensor = torch.empty(3, 4).exponential_(1)
print("\nExponential Tensor:\n", exponential_tensor)

# 5. 布尔分布
# 生成一个形状为(3, 4)的张量，元素服从布尔分布，概率为0.5
boolean_tensor = torch.randint(0, 2, (3, 4), dtype=torch.bool)
print("\nBoolean Tensor:\n", boolean_tensor)
# 6. 均匀分布采样
# 生成一个形状为(3, 4)的张量，元素在[0, 10)之间均匀分布
uniform_sample_tensor = torch.randint(0, 10, (3, 4))
print("\nUniform Sample Tensor:\n", uniform_sample_tensor)
# 7. 正态分布采样
# 生成一个形状为(3, 4)的张量，元素服从均值为5，标准差为2的正态分布
normal_sample_tensor = torch.normal(5, 2, (3, 4))
print("\nNormal Sample Tensor:\n", normal_sample_tensor)
# 8. 二项分布采样
# 生成一个形状为(3, 4)的张量，元素服从二项分布，n=10, p=0.5
binomial_sample_tensor = torch.bernoulli(torch.full((3, 4), 0.5)) * 10
print("\nBinomial Sample Tensor:\n", binomial_sample_tensor)
# 9. 指数分布采样
# 生成一个形状为(3, 4)的张量，元素服从参数为2的指数分布
exponential_sample_tensor = torch.empty(3, 4).exponential_(2)
print("\nExponential Sample Tensor:\n", exponential_sample_tensor)
# 10. 布尔分布采样
# 生成一个形状为(3, 4)的张量，元素服从布尔分布，概率为0.7
boolean_sample_tensor = torch.rand(3, 4) < 0.7
print("\nBoolean Sample Tensor:\n", boolean_sample_tensor)


Uniform Tensor:
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Normal Tensor:
 tensor([[ 2.2082, -0.6380,  0.4617,  0.2674],
        [ 0.5349,  0.8094,  1.1103, -1.6898],
        [-0.9890,  0.9580,  1.3221,  0.8172]])

Binomial Tensor:
 tensor([[0., 0., 0., 1.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.]])

Exponential Tensor:
 tensor([[0.0318, 0.0412, 2.6869, 0.1650],
        [0.3079, 0.1398, 0.2902, 0.2658],
        [0.2558, 0.3821, 0.9530, 0.9107]])

Boolean Tensor:
 tensor([[False,  True, False,  True],
        [ True,  True, False,  True],
        [False,  True, False,  True]])

Uniform Sample Tensor:
 tensor([[2, 0, 9, 8],
        [5, 3, 7, 7],
        [5, 9, 1, 5]])

Normal Sample Tensor:
 tensor([[ 3.6220,  2.7466,  4.4285,  2.8130],
        [ 7.2702,  6.5185, -2.1889,  5.0383],
        [ 5.2103,  6.9207,  3.8656,  3.8587]])

Binomial Sample Tensor:
 tensor([[ 0., 10., 10., 10.],
        [